sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: U4HKDdH249sTUgOmuU5Hc3pw1zKIY/FH8sLwChwUDZv21ZAFvPeS8qZtDjZwjNXfvKrKdQN8OKP2p1ESBiSxOWwC2U68MJwgDtpFMfTHd6NRo/9rHQDpVLNOiE2rngWfwCJS9KPPvMepviac9mb05aGaYOR5k1AmF1VHRhVAc+HIS5rYlx8Ey0pOeBRZe1rYwBxd7lhBqQUvCx0xxk3xkCeBjZNrLnsBSAxShxkUtRQgNxN4vQfaZaF19vE6avSBlsm8vH7X3COIE5UYXLvme0KsX4EfYm20iC9PpqO3xnGXaWOmJgw8/LeWXsdk4sxZmy0riAjQqA90m3O9u9/pdNNkFJxRQWP969lmaXR2FXPHvmwqW/6pUp7i3rd7gEZrkhGEjn8VkujA1nIL6dycm7hodVOwfk7Gxm4OnlFJJCvPa/PdmfM2lTryOJLvpJpvkH5xJVj/NLV0EqPl90vKIBkndgvNFgiiKBZ+4JYXtNJUKfBxMstcFy09noaU2T2rpvZ8d0+9SPX95XpRR/ATYJ/yLwtqPLSAuIQs1rPN6a7HjHGZm0n85ohMTrazZnKrBrxoRRbAz+Y1Wrg9r/YbjppzlGbVkX6Dr0cx6pyo2L4fBPN+k8OAen2eQ/dC0wJy206RtBtaHpmWpv4Vx+9d5rVJXuwFpEAiTyghFXofmF0=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: eIcKzl0IU+YJB4wrGHsRzWJksfM+7H2l1xZn4UC8bTc2WKKdP8y9hbHIjZdmilszKLmYVbaCjKZDlb9z1E+Ghv767Gni9U4pyHVqLZeJe3R3YC7/v0iF3FtL0Cwahlym91vH2dP9zrBYtUkwIn83mh4kfmLp6aehdrHuVkP4jY4SwVfrSoPZWDi+tjJgUIjkqHGKFE3PPjn30ZKqo8WqYoTo+33y3ccybfrP/MS5jEmDzzOiE1+mDmIwjiwhAkdYoqbsKUowfAiuUfDpWYYAjWQGq3inlcym6vq3Vg2mNLqpaul68nWmd/zQ2OeGwbhK0GI4uxZ/Sa521OEfzyPrNlgRe5D5VJKq0Rl2zGZtSPCUARDfGEHW4pW0H89ptKs6sNRy1lW+WQw1GjoQHZjpWjJVBIAyG43ZCkn4crH5fElbVYfVBiXqe/2ZM1T0tsrzw8Z3vaRQIkH23NCzsGNtE1aEbU4SuJZBzeBQwOLgaVxOU2Elsbi3189KeIodWzmZ7ni4mB3nJzAB4Lo9Nri0Te7zcqS/v2Tt/G4LDc5OgP+bphwIIzSSugRuVAkLp/ANWpOz9Dwut00bpVaJ6njKZQh3W/wjPj0QATs2CL3ZAesTuPoSNJ0DTlAOUE3zfreT1qEsY6FhmflVfx6xg9YqpS0CpZdDX1zfD4wTrFVE3RM=
